### ISSUE TITLE
Inserir data/hora de inicio e fim de cada stroke

### ISSUE THREAD

**Issue by JulianoShinohara** [JulianoShinohara/xournalpp#2]
Como professor, gostaria de saber o tempo de criação de cada stroke, para poder saber quanto tempo utilizei.

**Comment by magsilva** [comment]
No caso, não seria apenas o tempo, mas também a data da criação. Quanto ao benefício, o maior benefício é saber quando e qual foi a sequência das ações (strokes).

**Comment by Vanakaus** [comment]
Após muita procura nos arquivos e nos códigos não foi possível realizar a issue, porem aqui está todo o registro desse processo.

De início foi encontrado o arquivo "xournalpp\src\control\xml\XmlPointNode.cpp" que contem a chamada de função para escrita das strokes no arquivo .xopp, com isso foi adicionado os comandos: "time_t now = time(0);" para detectar o horário atual, "tm* localtm = localtime(&now);" para formatar o horário para o horário local, "out->write(" data:");" e "out->write(localtime);" para escrever no arquivo .xopp. Com isso foi feito o teste e obtivemos resultados promissores, porém ao realizar mais testes foi descoberto que as funções desse arquivo eram chamas apenas no momento que o arquivo era salvo, com isso todos os horários salvos no arquivo eram o mesmo horário e a cada vez q era salvo o arquivo o horário era sobrescrito para o horário em que ele foi salvo.

Então voltamos a estudar o código e com isso foi percebido q os atributos da stroke estavam salvas em outro local, a partir desse ponto pesquisamos em que parte do código era feito o salvamento dos atributos da stroke, para junto desses atributos ser adicionado os horários, porém nesse momento foi pedido a ajuda do professor, que nos ajudou e indicou os seguintes arquivos para pesquisa aprofundada:
-"xournala/ppsrc/control/xojfile/SaveHandler.cpp";
-"xournala/src/model/Stroke.cpp";
-"xournala/src/control/tools/StrokeHandler.cpp";
-"xournala/src/gui/inputdevices/PenInputHandler.h".

Então encontramos o metodo: "stroke->setAttrib("data", DADOS, STRING)" que adicionava os atributos a stroke, após isso mais testes foram feitos, o atributo era adicionado a stroke e escrito no arquivo .xopp, mas os horários continuavam sendo o momento em que o arquivo era salvo e não no momento em que a ação era realizada. Então com este avanço precisávamos achar qual parte do código era executado no momento das ações. Infelizmente não obtivemos sucesso nessa tarefa, apesar das diversas pesquisas com testes, inclusive em partes dos código relacionado a coleta das coordenadas da stroke, mas com o mesmo resultado, os horários escritos no arquivo .xopp continuava sendo o horário de salvamento do arquivo.
